// Generated by gencpp from file carla_ros_scenario_runner_types/ExecuteScenarioRequest.msg
// DO NOT EDIT!


#ifndef CARLA_ROS_SCENARIO_RUNNER_TYPES_MESSAGE_EXECUTESCENARIOREQUEST_H
#define CARLA_ROS_SCENARIO_RUNNER_TYPES_MESSAGE_EXECUTESCENARIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <carla_ros_scenario_runner_types/CarlaScenario.h>

namespace carla_ros_scenario_runner_types
{
template <class ContainerAllocator>
struct ExecuteScenarioRequest_
{
  typedef ExecuteScenarioRequest_<ContainerAllocator> Type;

  ExecuteScenarioRequest_()
    : scenario()  {
    }
  ExecuteScenarioRequest_(const ContainerAllocator& _alloc)
    : scenario(_alloc)  {
  (void)_alloc;
    }



   typedef  ::carla_ros_scenario_runner_types::CarlaScenario_<ContainerAllocator>  _scenario_type;
  _scenario_type scenario;





  typedef boost::shared_ptr< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteScenarioRequest_

typedef ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<std::allocator<void> > ExecuteScenarioRequest;

typedef boost::shared_ptr< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest > ExecuteScenarioRequestPtr;
typedef boost::shared_ptr< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest const> ExecuteScenarioRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace carla_ros_scenario_runner_types

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'carla_ros_scenario_runner_types': ['/home/himanshu/carla-ros-bridge/catkin_ws/src/carla_ros_scenario_runner_types/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbb073181f183d07c3de4418b78e4cd3";
  }

  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbb073181f183d07ULL;
  static const uint64_t static_value2 = 0xc3de4418b78e4cd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carla_ros_scenario_runner_types/ExecuteScenarioRequest";
  }

  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"CarlaScenario scenario\n"
"\n"
"================================================================================\n"
"MSG: carla_ros_scenario_runner_types/CarlaScenario\n"
"#\n"
"# Copyright (c) 2020 Intel Corporation.\n"
"#\n"
"# This work is licensed under the terms of the MIT license.\n"
"# For a copy, see <https://opensource.org/licenses/MIT>.\n"
"#\n"
"string name\n"
"string scenario_file\n"
"geometry_msgs/Pose destination\n"
"float64 target_speed\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.scenario);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteScenarioRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator>& v)
  {
    s << indent << "scenario: ";
    s << std::endl;
    Printer< ::carla_ros_scenario_runner_types::CarlaScenario_<ContainerAllocator> >::stream(s, indent + "  ", v.scenario);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARLA_ROS_SCENARIO_RUNNER_TYPES_MESSAGE_EXECUTESCENARIOREQUEST_H
